matrix:
  include:
    - language: python
      python: 3.6 
      before_script:
        - sudo apt-get -y install python3.6
        - sudo apt-get -y install python3.pip
        - pip3 install symp

    - language: cpp
    compiler:
        - gcc
        - clang 
      os: linux
      before_script:
        - bash
      script:
        - g++ Analizador.cpp
        - ./a.out -i Pruebas.txt*/